# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  port: 3306
  # socket: /tmp/mysql.sock
development:
  <<: *default
  database: MaroueneMaamar_development
#
#   production:
#   url: <%= ENV['DATABASE_URL'] %>
  # adapter: mysql2
  # encoding: utf8
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: codeboxx
  # password: Codeboxx1!
  # host: codeboxx.cq6zrczewpu2.us-east-1.rds.amazonaws.com
  # port: 3306
#
# production:
#   <<: *default
#   database: Application_production
#   username: Application
#   password: <%= ENV['APPLICATION_DATABASE_PASSWORD'] %>

  production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: codeboxx
  password: Codeboxx1!
  host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com
  port: 5432

# test:
#   <<: *default
#   database: MaroueneMaamar_test





