production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: codeboxx
  password: Codeboxx1!
  host: codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: codeboxx
  host: localhost
  database: datawarehouse

# test:
#   <<: *default
#   database: MaroueneMaamar_test


